name: Docker Build and Upload

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
  schedule:
    # once a week
    - cron:  '0 0 * * 1'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  DOCKER_TAG: ${{ github.repository_owner }}/packer-builder-arm:latest

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      #### run lint, build+export, test only on PRs
      - name: Lint
        if: github.event_name == 'pull_request'
        run: |
          docker run --rm -i ghcr.io/hadolint/hadolint < docker/Dockerfile
          shellcheck --enable=all docker/entrypoint.sh

      - name: Build and export to Docker
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/Dockerfile
          load: true
          tags: |
            ${{ env.DOCKER_TAG }}

      - name: Test
        if: github.event_name == 'pull_request'
        run: |
          docker run --rm --privileged -v /dev:/dev -v ${PWD}:/build ${{ env.DOCKER_TAG }} build boards/raspberry-pi-4/archlinuxarm.json -extra-system-packages=bmap-tools,zstd;
          du -h raspberry-pi-4.img
          du -h --apparent-size raspberry-pi-4.img
      ####

      - name: Login to DockerHub
        uses: docker/login-action@v2
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GHCR_IO_REGISTRY_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        if: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags') }}
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.DOCKER_TAG }}
          # ghcr.io/${{ github.repository_owner }}/packer-builder-arm:latest
